CREATE TABLE bcomment(cno DOUBLE,bno DOUBLE,userid VARCHAR(10),cstar DOUBLE,ccontent VARCHAR(10));
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (1,1,'root',3,'단연 최고라고 할수있지');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (2,2,'roots',3,'감독이 럼먹고 영화를 만들었나보다.. 관객에게 뭘 말하는지도 모르겠고, 엉망진창 개진창이다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (3,3,'toor',3,'이건 뭐냐? 우뢰매냐? ;;;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (4,4,'admin',3,'정말쓰레기영화입니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (5,5,'clio',3,'진정 위대한 영화 최고임');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (6,6,'akas22',3,'별루 였다..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (7,7,'olus',3,'내일이 기대되는 `');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (8,8,'bava',3,'근데 조미가 막문위 좋아한건가요??');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (9,9,'dita',3,'ㅋㅋㅋ 진짜 골깜..ㅋㅋ 눈 부라릴때 쓰러짐..ㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (10,10,'erim1',3,'성룡영화중 최악인듯 ㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (11,11,'guba',3,'골때리네ㅋㅋㅋㅋ 걸스데이 이혜리 잘 되라!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (12,12,'otto',3,'서기가이뻐서');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (13,13,'euda',3,'완전 재밌어요ㅋㅋㅋㅋㅋ백인공주귀여움ㅋㅋㅋㅋㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (14,14,'mahga3',3,'인상적인 영화였다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (15,15,'leon',3,'어내스트와 셀레스틴 완전 강추에요~ 정말 재밌습니다^^');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (16,16,'cosma123',3,'재미있는영화입니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (17,17,'carbbo',3,'클라라볼라고화신본거아닌데');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (18,18,'nucca',3,'진짜 보면서 너무 슬펐던 영화다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (19,19,'julia',3,'설정이 재밌고 새로운 에피소드 내에서 메인 스토리도 차차 나오는게 재밌음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (20,20,'tillo11',3,'신카이 마코토의 작화와,미유와 하나카나가 연기를 잘해줘서 더대박이였다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (21,21,'samsam1',3,'재미없음 진심 1이훨나 캐스팅두못한듯');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (22,22,'hihi1123',3,'잔잔한게 생각보다 볼만한 영화인거 같습니다 ㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (23,23,'root',3,'감독님들 고은님 쓰면 영화안봅니다 .');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (24,24,'roots',3,'무섭지도 않았고 스토리도 ..ㅡㅡ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (25,25,'toor',3,'영화속 억지스럽고 노골적인 술광고를 좀 은은하고 센스있게 했으면 어땠을까?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (26,26,'admin',3,'킬링타임');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (27,27,'clio',3,'크리스마스하면 떠오르는영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (28,28,'akas22',3,'재미있게 봤습니다. 매력적인 행복이네요, '-' ㅎㅎㅎ.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (29,29,'olus',3,'음악에 완전히 빠져서 볼 수 있었던 영화. 쫌 산만하긴 하던데;;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (30,30,'bava',3,'태어나서 처음으로 영화보다 중간에 나왔습니다,,,,불륜이 로맨스냐,,');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (31,31,'dita',3,'왕짜증.....아주 전개를 짬뽕으로 믹스했구나...음향만 무섭게하네..하아');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (32,32,'erim1',3,'솔직히 난 별루더라 시간낭비느낌');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (33,33,'guba',3,'대박');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (34,34,'otto',3,'시청률 기준이 되는 패널가구들 머하는거지 명작드라마 다 망치네 ㅡㅡ 내가 다 서운하다...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (35,35,'euda',3,'내용이 이상해;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (36,36,'mahga3',3,'몬스터 주식회사 3D 재밌게 봤다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (37,37,'leon',3,'내용전개가 너무나 느리다........');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (38,38,'cosma123',3,'소재는 흥미를 끌지만 이야기 전개가 투박해서 몰입이 안되는군');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (39,39,'carbbo',3,'절대 보지마라 쓰레기 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (40,40,'nucca',3,'중국인 특유의 과장, 허풍... 있어보이려고 안간힘 쓴 노력은 가상하나, 고증과 현실감 떨어지는 설정이 거북스럽다... 도대체 그들은 왜 이렇게까지 스스로를 과대포장하는 것인지...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (41,41,'julia',3,'그냥 불법체류자 때려잡는 영화면 좋았을텐데...무슨 우상화를 만든다고 미국의 따뜻한 설정...이건 뭥미??');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (42,42,'tillo11',3,'2년의 삶속에 주인공의 생애가 전부 드러난 듯 하다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (43,43,'samsam1',3,'별점10점가자');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (44,44,'hihi1123',3,'별로다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (45,45,'root',3,'본지 꽤 지난 후에 남기지만...재미있었음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (46,46,'roots',3,'아니 이게 왜 9점대 일까...;;;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (47,47,'toor',3,'10년이 지나 다시 보게된 영화 .. 다시봐도 그 순수한 사랑에 감동 ㅠㅠ 숀펜의 연기또한 甲');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (48,48,'admin',3,'올레에 공짜로있길래 봤음 ㅋㅋ 헐 ... 스토리가 문제가아니라 연기자들이 전혀 배역이랑 어울리지않음 그리고 상대배우들하고 다 따로 노는거같음~~ 이건 연기자들도 문제있음 보아는 진심 완전 별로임 라미란하고 아들이 젤 볼만했음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (49,49,'clio',3,'너무 욕심이 많았던 영화. 어느 한 쪽만이라도 제대로 보여줬다면......');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (50,50,'akas22',3,'아 빵점~');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (51,51,'olus',3,'베댓이 말을 아주 잘써놨네');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (52,52,'bava',3,'아주 모자라진 않다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (53,53,'dita',3,'영화 도둑들이나 뫼비우스 하고 같은 나라에서 만들어졌다는게 믿어지냐..?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (54,54,'erim1',3,'온몸이.. 찌릿..짜릿. 나두 용기를 가져야지!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (55,55,'guba',3,'정말재미있고 교훈적인 영화이네요!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (56,56,'otto',3,'당시의 상황과 주제를 주입식이 아닌 긴장감있고 재밌게 전하는 작품');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (57,57,'euda',3,'케이블에서 그만 나와줬으면 - -');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (58,58,'mahga3',3,'다르덴,이냐리투,차이밍량이 하나도 안섞인채 짬뽕 그릇에 담겨있다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (59,59,'leon',3,'여군 잼없음 뭐하는건지 ...ㅡㅡ잼없음 엠비씨 다잼없음 질린다이제');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (60,60,'cosma123',3,'좋구나');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (61,61,'carbbo',3,'한석규, 김혜수 연기만 돋보인 영화. 어딘지 모르게 많이 어설픈 영화.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (62,62,'nucca',3,'솔직히 에볼라바이러스가 떠들석해서 보게된영화인데 작품성이나 어떤면에서도 20여년전 영화라고보기엔 믿기힘들정도로 정말 잘만들었다고본다 마지막후반부가 살짝 아쉽긴하지만 이정도면 수작이라고본다 시간이 아깝지않은영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (63,63,'julia',3,'볼만해;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (64,64,'tillo11',3,'재미있다고 허풍 떨지 마세요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (65,65,'samsam1',3,'용가리 진짜짱짱맨이다ㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (66,66,'hihi1123',3,'이 영화를 이제서야 보다니.. 감히 내 인생 최고의 영화중 하나로 꼽을 수 있을만한 작품. 어떻게 살아야할지 나를 위한 고민을 한번 더 하게 되는 시간. 그리고 모건 프리먼은 나이가 들어도 여전히 섹시하다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (67,67,'root',3,'작가가별로다 내용이진짜별로임.. 맨날그냥기대하고 재방송하면 혹시나하고봐줘도 답없다진짜..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (68,68,'roots',3,'명작도 이런 명작이 있을까 싶다. 보고 또 봐도 여운이 남는 영화.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (69,69,'toor',3,'아~ 진짜 조금만 더 손 좀 보면 왠만한 상업 영화 못지 않게 퀄리티 쩔게 만들어 질 수 있었는데 아쉽네요 그래도 충분히 재미있었습니다 개인적으로 조금만 더 잔인하게 더 자극적으로 노출씬도 화끈하게 했더라면 어땠을까 하는 국산영화라 많이 아낀 듯 보임');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (70,70,'admin',3,'그만좀 끌고 이제 끝내라. 지겹다 지겨워.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (71,71,'clio',3,'아');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (72,72,'akas22',3,'역시 드니로의 연기는 일품 나도 맥스가 샘을 죽이길 바랬다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (73,73,'olus',3,'나름 괜찮은 작품입니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (74,74,'bava',3,'너무 좋은 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (75,75,'dita',3,'정말 실망 스러웟음..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (76,76,'erim1',3,'배우들은 지네들 안뜨니까 이런영화 찍을껀데??? 왜 안뜨는지 진짜 모르는거야? 면상 딱 보면 알겠구만... 왜 지네 자신들은 모를까?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (77,77,'guba',3,'어린이가 좋아할듯...내어릴적 동심은 멀리 떠낫나보다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (78,78,'otto',3,'무술인이 왜 총을드나?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (79,79,'euda',3,'10점');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (80,80,'mahga3',3,'크리스토퍼왈츠와 타란티노의 조합이란 ㅠㅠ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (81,81,'leon',3,'한국에선유명한편은아니지만 외국에선 상상초월한 유명한 영화입니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (82,82,'cosma123',3,'오랜만에 재밋는영화봤네요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (83,83,'carbbo',3,'종방되어 아쉬워요. 오늘막방도 잘봤어요.방송대본이 꽤 완성도있다는 느낌받았고요. 요즘 드라마들의 막장에 지쳐있었는데 수백향은 정말 바른드라마였던듯해요.악역들도 그리 심하게 어이없지도 않았고요..MBC화이팅!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (84,84,'nucca',3,'평점조절위원회에서 나왔습니다(웃음)김혜선은 @내일이 오면@의 김순정,순정이 역할이 제일이다.팜므파탈로써,그 정도까지 잘해낼 줄은,정말 의외였어...연기20년 한사람에게 요즘 사극에서 벌어지고 있는,그녀에 대한 연기논란은 왠지 코미디의한장면 같음(웃음)');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (85,85,'julia',3,'"""영화 끝나갈때쯤에 멍하다가 다보고나면 한마디 나올거임 """"ㅈ같다."""""""');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (86,86,'tillo11',3,'공유 존잘!!!ㅎㅎㅎ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (87,87,'samsam1',3,'상쾌발랄한 영화다. 말하기 껄끄런 성이란 소재를 유쾌하게 해설했다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (88,88,'hihi1123',3,'소파에 죽 치고 앉아 지켜 볼 이유가 없는 작품.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (89,89,'root',3,'로큰롤!!!!!!!!!!!!!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (90,90,'roots',3,'주된 타겟이 어린이니 일반적인 논리가 통하지 않는 건 알겠다. 하지만 게임은 흥미롭지 않고, 요원이라는 주인공이 너무 무능력해서 별로 재미없다. CG 배경도 거슬린다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (91,91,'toor',3,'뮤지컬 영화인데 사운드 녹음 엉망, 남주는 춤도 못추고, 내용은 뻔할뻔, 주인공들 목소리도 너무 안어울리고 어제 CGV에서 뛰어 나가려다 참았습니다.진심 말리고 싶습니다. 영국의 저예산 DVD용 영화뮤지컬영화 아닙니다. 맘마미아 1/10도 안됨');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (92,92,'admin',3,'어린나이에 봤음에도 꽤나 좋아했던 로맨틱코미디');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (93,93,'clio',3,'게이물인줄 모르고 봤네...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (94,94,'akas22',3,'알바는꺼저라');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (95,95,'olus',3,'이 영화 머임????내가 왜 받아 봤을까? 그것이 알고싶다....이 영화는 배우들과 스텝들이 감독의 꼭두각시였음.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (96,96,'bava',3,'4대2라니....최악');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (97,97,'dita',3,'정말 아름다운 영화 입니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (98,98,'erim1',3,'자극적인 것에 익숙해진 현대인이 봐도 눈을 떼기 힘든 연출력.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (99,99,'guba',3,'뻑~뻑~잘 읽어볼걸 나도 당했음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (100,100,'otto',3,'정말 짜증의 극치를 보여주는영화. 굉장히 언밸러스한 느낌. 뚱뚱하고 못생긴 남자애의 발연기를 시종일관 봐야하는게 고역인듯. 간간히 흘러나오는 잔잔한 클래식풍의 음악조차도 듣기싫어 짜증날정도로 상당히 싫은영화.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (101,101,'euda',3,'감동감동ㅜㅜ, 정말 최고네요!!!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (102,102,'mahga3',3,'별점 주기도 아깝네요 얼마나 내용이 진부한지 욕 밖에 안나오네요보고 재밌다고 하는 사람 초딩들인가요 죄송해요 너무 화가나서.아무 것도 볼게 없습니다 보지 마세요 그냥 티비판짜집기 한거 같네요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (103,103,'leon',3,'나 왠만해서 짜증안내는데...-_-');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (104,104,'cosma123',3,'돼지피먹고 닭목따는 장면에선 우웩~ 역시 무당은 아무나 하는게 아니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (105,105,'carbbo',3,'버려');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (106,106,'nucca',3,'유치하고 지루하고 잠이 왔다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (107,107,'julia',3,'3류풍 판타지 3점만 가져가');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (108,108,'tillo11',3,'윤종신 복귀는 좋았지만 이하늘은 도대체 왜 뽑혔는지 알수가없다. 참가자 실력을 따지기 전에 심사위원 인격과 실력부터 쌓고 오시길^^ 어하어허 그만좀 하고요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (109,109,'samsam1',3,'광장한 작품 옛날것도 보고 싶다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (110,110,'hihi1123',3,'내 생의 최고의 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (111,111,'root',3,'어린시절 너무 무섭고 재미있게 봤던 추억의 판타지영화.절대 나쁜짓은 금물.지옥가요..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (112,112,'roots',3,'기존 멜로영화 형식을 탈피하려고 하였으나 감정의 절제가 지나쳐 너무 담백한 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (113,113,'toor',3,'난 사랑비 서준에게 쏙 빠져버렸네. 1.2.3초만에 쏙ㅋㅋ난 절대잊지도않고후회도안할거야');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (114,114,'admin',3,'이영화를보니까 교훈을 주네요! 나도 남은인생을 화려하게 살아야겟다.. 말밖에 안나오네요..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (115,115,'clio',3,'나름 추억에 젖어들고 좋았음ㅋㅋ아무생각없이 가볍게 보고오기 추천요~');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (116,116,'akas22',3,'단순한 싸이코물을 벗어난');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (117,117,'olus',3,'이게 14년도에 만들어진건가요? 아니면 예전에 만든거 다시개봉한건가요?ㅠ너무 허접해요 ㅠ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (118,118,'bava',3,'넘 사랑스러운 영화다 ㅠㅠ 1보고 2 연이어 봤다~!! 넘 귀여워 ㅠㅠ♥♥');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (119,119,'dita',3,'청춘 영화만이 줄 수 있는 감성이 넘쳐난다. 이 순간 지나가면 다시 돌아오지 않을테지만, 그 순간만큼은 무한할 젊음이 줄 수 있는 그런 감성.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (120,120,'erim1',3,'TV용 건담 시리즈 중에서 아직까지도 최고봉');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (121,121,'guba',3,'개콘은 요즘 갈수록 코너들이 다노잼이고 웃음이안난다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (122,122,'otto',3,'사다코의 한이 서린 우물펀치ㅜㅜ 감동');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (123,123,'euda',3,'후세와 사랑하게된 결정적 계기 그시간이 표현되지 않았으며 시람의 생명을 빼앗아야만하는이유등을 시노가 출현하는 연극으 로 더 알려주었으면 하는 생각이든다. 또한 시노가 얼마나 본능을절제히면서 시랑을 하려고 노력하는지를 더 보여줬다면 좋았을뻔했다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (124,124,'mahga3',3,'새벽시간에 하는 일본 영화들은 전부 개졸작이다.일본영화원래 다이래??');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (125,125,'leon',3,'강수연의 나가있어~!그리고 최정원의 신음신~');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (126,126,'cosma123',3,'아..정말 김혜성 너무 예쁘네요 이현진도 웃는 거 정말...하....');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (127,127,'carbbo',3,'가발 쓰고 싶다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (128,128,'nucca',3,'화려한여정이인상깊어요ㅋㅋ재밋어요ㅋㅋ배두나연기정말잘해요ㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (129,129,'julia',3,'10대들을 위한 성적 호기심 영화?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (130,130,'tillo11',3,'감동적인 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (131,131,'samsam1',3,'이건 말이 필요 없다 그냥 닥치고 봐라');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (132,132,'hihi1123',3,'각기 다른 사람들의 재밌고 멋진 사랑영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (133,133,'root',3,'역시 미국드라마의 파워. 정말 알수없는 그 미묘함까지 사로잡아버렸다 최고!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (134,134,'roots',3,'너무너무 훈훈하네요^^');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (135,135,'toor',3,'이거 응답하라에서 은지원원도 스스로 욕하지 않앗나? ㅋㅋㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (136,136,'admin',3,'아 너무 웃기고 배꼽 빠질뻔했네^^ 내 컴에 이 영화 있는데^^');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (137,137,'clio',3,'구성이 상당히 부실한 영화. 역시 네이버 평점은 믿을수 없다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (138,138,'akas22',3,'장끌로드의 몰락을 가져온 오우삼 헐리우드 작품중 가장 재미없었던 졸작');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (139,139,'olus',3,'언제적 영웅본색 연출인지 현실성 제로인 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (140,140,'bava',3,'작은거 하나에도 설레어했던 학창시절 그때 그느낌을 다시 느껴볼수있는시간이었다. 장면 하나 하나 대사 하나 하나 배경음악 하나 하나 버릴게 없는 드라마.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (141,141,'dita',3,'진심 재미 없는데 너무 평점 높아서 화남;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (142,142,'erim1',3,'더럽게 재미없다 어떤 형태로도 와 닿지 않는 허무하고 완벽히 지루한 영화고 영양가 하나도 없는 영화다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (143,143,'guba',3,'이승기 정말 연기 잘하는.. 조연들도 연기 정말 잘하고');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (144,144,'otto',3,'현실은 꿈, 꿈은 현실');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (145,145,'euda',3,'오늘 현충일특집프로로 보게되었습니다 1963년도의 매우 훌륭한 작품입니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (146,146,'mahga3',3,'판의미로와 동급 trash of the trash');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (147,147,'leon',3,'제대하고 보니까 더 재밌네요 ㅋㅋㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (148,148,'cosma123',3,'영화를 보는것만으로도 마음의 휴가를 다녀온 느낌.소박하지고 잔잔하지만 지루하지않은..그래서 다시 보고싶은 영화.햇살가득한 비이의 부엌과 요리도 인상적');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (149,149,'carbbo',3,'코믹한건 좋았는데 짜임새가 너무 허술하다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (150,150,'nucca',3,'1996년 그때 당시에는 우리 나라에 이런 판타지 로맨스가 없었다... 아직도 신현준의 황장군 연기는 음... 괜찮네... ㅎㅎ....한석규의 전성시대가 열린 영화.... 이때 한석규한테 뿅 갔었다~~♥');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (151,1,'julia',4,'일단 재생하면 괴물같은 서스펜스 귀신같은 흡입력');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (152,2,'tillo11',4,'하..진짜 댓글보고 한번쯤볼만한 영화인거같아서봤지만 기가찬다..이게무슨버킷리스트인가! 죽기직전에 소원들어주기? 내가보기엔 죽기직전에 막 살자 인거같다. 감동도없고.. 진짜 '버킷리스트' 란 영화에 발톱에 때만큼도 못따라가는쓰레기영화.. 완존실망..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (153,3,'samsam1',3,'이시간좀...밝고긍정적인드라마보고싶어서..보긴보는데....오버하는연기들이거슬리네요...연기인게너무표나요....홍혜정역이그나마도후련기도하고시원하고.....나머진다들답답하네요...낼월요일인데...해피한것만보고싶네요....');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (154,4,'hihi1123',5,'정치인의 모순인가, 정치범의 모순인가....');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (155,5,'root',4,'어떻게 이런 상상을 대단하다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (156,6,'roots',5,'좀 어렵기도 하고, 전쟁에 대한 묘사가... 잘 모르겠다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (157,7,'toor',3,'일본에서10주년 극장판만드는데 우리나라에선 10주년으로 재개봉하니이건 좀 ㅄ 아님?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (158,8,'admin',3,'한대희가 개그콘서트본다고 내전화끊음개그콘서트 없애주세요 ㅡㅡ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (159,9,'clio',1,'한물 간 동서양 두 배우의 싸움판.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (160,10,'akas22',2,'푸하하하 이거 기대 안했지만.. 역시나 구만..ㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (161,11,'olus',3,'세계최초의 반공 애니매이션이라는 역사적 가치가 있다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (162,12,'bava',5,'감각적인..시각으로...바라보는..색다른...느낌의...사랑...문학적이');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (163,13,'dita',5,'엄마는 무고한 지 딸을 감옥살이 시켜시켜? 이해 안돼요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (164,14,'erim1',3,'이영화는.제발 책을보세여.감독이 미친겁니다.이따위로 만들어놓고.화가 날정도 ㅡㅡ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (165,15,'guba',4,'신나는 흑인음악과 아이스 큐브 뿐 남는게 없다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (166,16,'otto',2,'드럽게 재미없네 시간이 돈이다? 내 시간은 어쩔건데');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (167,17,'euda',4,'그저 한마디뿐 '알리시아'');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (168,18,'mahga3',3,'진짜 생생하게 느낄 수 있었다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (169,19,'leon',1,'재밌는데 평점이 이상하다 싶을 정도로 낮다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (170,20,'cosma123',5,'옥소리 프로필 사진에 1점남기고 갑니다 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ완전 대박이다 진짜 아우 짜증나!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (171,21,'carbbo',4,'드라마 너무 재밓당');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (172,22,'nucca',2,'아진짜너무좋아요ㅜㅜ짱짱!!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (173,23,'julia',4,'연기 굿');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (174,24,'tillo11',1,'이런 영화 다시는 안나오겠지..그때 시절을 잘나타내주었던거같아요 ㅎㅎ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (175,25,'samsam1',1,'중간정도 부터 봤는데도 꽤나 대단하군요...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (176,26,'hihi1123',1,'콩은 까야 제맛 콩은 까야 제맛');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (177,27,'root',3,'이적의 소설. 재미없다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (178,28,'roots',2,'액션영화가 아니다.범죄 느와르 영화다. 허나 범죄 느와르 영화로서도 실패작.......');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (179,29,'toor',2,'뭔가알수없는매력에빠져드는 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (180,30,'admin',1,'모녀를 토막살해한 살인자가 부성애라니.... 말이되나... 감동받은 사람들 본인들이 피해자가 되도 감동받았다고 할수있을까... 진심 묻고싶습니다...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (181,31,'clio',2,'재밌는데 평점이 왜 이렇게 구리지');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (182,32,'akas22',2,'아 OOO기.. 이걸 본 내눈이 아깝다 ㅡㅡ 진짜 아놔 진짜 OOO기명작이네요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (183,33,'olus',5,'필름값이 아깝다..재미 더럽게없다..2점부터 점수준것들 매미 OO');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (184,34,'bava',4,'또보고 싶은데 어디서 보죠???');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (185,35,'dita',1,'영화 재미있드만.. ㅎㅎ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (186,36,'erim1',4,'남주인공 연기력 안습이네요... 혀짧은 소리 듣기도 너무 힘들었네요 매니저역활분이 남주인공하는게 훨 좋았겠다는 생각이 들정도... 영화 자체는 적당히 볼 만 합니다 ^^');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (187,37,'guba',5,'3점이 딱.... 액션,스릴러인데 액션과 스릴이 없다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (188,38,'otto',5,'완전 스토리도 엉망이구, 완전 비추..ㅜ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (189,39,'euda',5,'OOO영화 뭘전달하려는지모르겠네 오글거리고');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (190,40,'mahga3',1,'좋은영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (191,41,'leon',4,'......더빙이 이상해요.....할머니는 월래익숙한 ㄷㅔ.....');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (192,42,'cosma123',4,'이게 2편이 나왔어???');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (193,43,'carbbo',1,'모든게 2%씩 다 부족했다...아니..50%씩...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (194,44,'nucca',3,'정말 말 그대로 '쇼'하는 영화..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (195,45,'julia',4,'12년 전에 봐서 기억이 나질 않지만 진개가(천카이거) 감독 이름 세 자는 기억해 두었던.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (196,46,'tillo11',4,'정은지 언니!! 연기 잘하구..노래도 잘부르시고! 마지막회 웃으면서 즐겁게! 봤습니다! 트로트의 연인!♥');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (197,47,'samsam1',2,'이게 웃겨?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (198,48,'hihi1123',2,'망함');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (199,49,'root',5,'아이의 시선으로 보는 전쟁.., 보는 내내 가슴이 먹먹했다는...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (200,50,'roots',1,'사람들이 재미없다고 해서 레알 기대 안했는데 생각보다 볼만함. 근데 여자애랑 복순이랑 다투는 장면? 그건 굳이 없어도 됐다고 생각함 몰입도 겁나 없애고, 어색해보였음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (201,51,'toor',5,'설정이 연속극같은 느낌이 든다. 하지만 배우들의 연기가 뛰어나다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (202,52,'admin',3,'여주인공 인터뷰할때 지루해죽는줄알았음 ㅡㅡ 그냥저냥 킬링타임용 스릴러');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (203,53,'clio',5,'전미 박스 오피스1위 ㅋㅋ 그냥 몰아주기 하는건가 어떻게 이런영화가 1위를 하지 옛날 80~90년대 우뢰매수준의 물폭탄싸움이네 ㅋㅋ 손에서 빔나가나 손에서 물폭탄 나가나 다를게 뭐지?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (204,54,'akas22',1,'감독이 여자다보니 기량이 많이 딸리네');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (205,55,'olus',5,'또 보고 또 울.었.다..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (206,56,'bava',5,'이런 영화는 하나의 개연성만 없어도 허무하게 만들어 버린다. 조디포스터의 이쁜 모습만 남을 영화.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (207,57,'dita',4,'굳굳');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (208,58,'erim1',2,'스토리도 말이 안되고 개막장 사랑이야기도 아니예요 이걸보고계신다면 당신의 시간과돈을 아낀거예요^.^휴 그래도 본다면 호구');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (209,59,'guba',5,'네놈을 살려두기엔 쌀이 아까워! 세기의 명대사');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (210,60,'otto',3,'평점이 너무 높다. 전혀 재미있지 않았다. 쓸데없이 말만 많음. 이런 류의 영화는 조연들의 뒷받침이 중요한데 조연들의 내용자체가 전혀 없음. 또한 여배우도 별로 매력 없었다. 이틀전에 저스트고위드잇의 애니스톤을 보고 이 영화를 봐서 그런가. 실망했음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (211,61,'euda',2,'맛깔 나는 드라마.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (212,62,'mahga3',4,'시베리아인가 거기가서 훈련할때나오는 ost 개작살');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (213,63,'leon',1,'이건 시종일관 질~~질왜? 제목이 야경꾼 일지냐고 지금 10회가 넘어가는데 즉 2달이 넘어가는데. 앞에서 누군가가 얘기 하더만 이거 100부작이냐고 그러다 또 한 순간에 모든걸 훅진짜 지루함의 지존');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (214,64,'cosma123',2,'나이들수록 이해가 가는 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (215,65,'carbbo',2,'ㅠㅠ 슬픔');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (216,66,'nucca',3,'장면 개연성도 없고 아역은 연기도 못하고 무슨 추노에 나오는 민폐언년 외국판인줄....초반만 그럴싸한 저급영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (217,67,'julia',3,'이 영화 정말 별루예요. 결말이 이상해요....');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (218,68,'tillo11',5,'딱히 재미는 없네요 킁;;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (219,69,'samsam1',4,'완전재미있어요.애들도보기에알맞는듯');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (220,70,'hihi1123',1,'잔인하기도 하고 무서웠어요ㅠ탑은 멋있더라구요~~');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (221,71,'root',2,'무섭지도 않고 기분만 나쁘고 쩝');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (222,72,'roots',3,'군더더기 없는 깔끔한 그러나 강한 메세지 전달. 뜻밖의 참좋은 영화..!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (223,73,'toor',1,'이 영화는 최고다. 그냥 최고야 그런 줄 알아');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (224,74,'admin',1,'그랜드 부다페스트 호텔과 시리즈 같네.. 캐스팅이 아까워~');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (225,75,'clio',3,'빨리감기해서 봤음...투자비는 많이 들었을 것 같은데...영화사 망했네~ㅎ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (226,76,'akas22',4,'도대체 뭐가 재밌다는건지 모르겠네요 무슨 아이언맨 시리즈의 개그도 뛰어넘는다 하는데 어디서 웃어야할지도 모르겠고 내용도 뭔지 뜬금없는 히어로놀이는 또 뭔지.. 왜이렇게 평점이 높은지 모르겠습니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (227,77,'olus',1,'왜 극을 끌어가는 중심있는 캐릭터가 있어야 하는지 알게 된영화 살인마와 대적하는 그리고 사건을 해결하는 인물이 없고 그리고 왜 마지막에 다 탈출 해놓고 나서 잡히고 죽임을 당하는지 이해할수가 없다. 대체 조달환 정유미는 왜 나옴?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (228,78,'bava',3,'진 짜 리얼 개 쓰레기 영화 . 다 보고 나면 정말 찝찝해지는 영화 절대보지마');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (229,79,'dita',3,'비록 로봇이지만 점차 인간의 감정을 가지고 자신에 대해 고민하면서 결국 인간이 되어 죽는 앤드류의 모습내가 봤던 영화 중에서도 최고의 감동을 선사한 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (230,80,'erim1',4,'영구와땡칠이시리즈는 레전드영화다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (231,81,'guba',2,'초딩 때 친척형이 비디오로 빌려와서 봤던 기억이 난다...너무 재미 없었다 근데 나중에 우연히 다시보니 재밌더라 그 땐 왜 그렇게 재미가 없었을까?? 98년이면 내가 초등학교 2학년 때니까...사촌형이 당시 나름 최신 비디오를 빌려온거 같다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (232,82,'otto',1,'지루할만큼 고요하고 서글픈 시선속에 머문 깊은 성찰과 사색.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (233,83,'euda',4,'영화 진짜 보고 .. 펑펑울었습니다 , 너무슬픈거같아요 .. ㅜㅜㅜ !');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (234,84,'mahga3',1,'누가 더 혀짧은가 내기하면 박빙일것같다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (235,85,'leon',5,'애 둘 딸린 심은하의 그 눈부신 미모, 아름다운 영상, 메인 주제가');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (236,86,'cosma123',4,'3기 나오겠죠 ? 아직 안풀린 이야기들이 많은데 극장판은 정말 시간가는줄도 모르고 봤네요 역시 싸패..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (237,87,'carbbo',3,'개노잼;; 뭔가 스토리도 부족하고 다이상함 진짜;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (238,88,'nucca',4,'답없네, 뭐하는건지..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (239,89,'julia',1,'절망과 슬픔 속에서도 자신을 챙겨야만하는 삶의 잔인함을 거부한 비참함에 대하여');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (240,90,'tillo11',5,'페이스 허거 같음ㅋㅋㅋㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (241,91,'samsam1',3,'시간이 흘러도 퇴색되지 않는 맛이 있는 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (242,92,'hihi1123',5,'진짜 어마어마한 여운을 주는 멜로 영화에요.ㅎ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (243,93,'root',4,'소피마르소와의 말같지도 않은 불륜이 내용 다 망침. 물론 실제 역사에는 그런 똥같은 이야기는 전혀 없었음.(주인공 죽을때 공주는 10살이었음)한마디.만약 미국인과 맞서 싸우는 아메리칸 원주민의 자유 투쟁기였으면 절대 아카데미상 못 받았음.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (244,94,'roots',5,'훈훈하고 따뜻한 부정을 느낄수잇엇음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (245,95,'toor',4,'잼');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (246,96,'admin',5,'전 정말 재미있게 봤습니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (247,97,'clio',4,'어딘가에서 일어나고 일일것같은 느낌이 강하다.우베볼이 이런 영화를 만드는 이유는 누군가 실제로 따라 했으면 하고 바라는것 같은데 정장 월가 있는 애들이 보면 웃겠지...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (248,98,'akas22',1,'림프비즈킷의 OST만 10점. 개봉 당시 극장에서 봤는데 영화내내 오우삼 쥑이고 싶었던ㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (249,99,'olus',2,'견자단 대박!!엽문 시리즈는 계속된다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (250,100,'bava',1,'정말 오월의 멜로는 정말로 보고보고 또봐도 계속 보고싶은 영화순위 1순위다하,,,늦은 밤이라 그런지 야릇한 느낌이 들었다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (251,101,'dita',4,'흥미롭게 봤어요. 여배우들 이쁘네요. 반했음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (252,102,'erim1',4,'스토리, 액션, 그래픽 머 하나 건질게 없는 망작. 그냥 게임으로나 즐기셔~');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (253,103,'guba',1,'그냥 레전드다 레전드!!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (254,104,'otto',1,'평론가 명치를 겁나 때리고 싶다. 정말 이 영화 재미없을거라 생각했는데 재미도 있고 내 인생에 도움이 가장큰 영화입니다. 본인이 깨달고 싶으면 꼭 보세요. 인생을 바꿔줄겁니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (255,105,'euda',4,'키아누 리브스 최고의 액션 영화!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (256,106,'mahga3',3,'소재가 아름다운 영화. 다소 아쉬운 부분들이 있는 이유는 이 영화는 영화스러운 극적 로맨스보단, 좀 더 사실적으로 한 남자의 마음과 시선을 말하고 싶었기 때문 아닐까.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (257,107,'leon',4,'영화평론가는 아니지만, 좋았다, 한번보고마는 영화가 아닌, 울림이있는영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (258,108,'cosma123',4,'역시 효느!!! 역시 재밌다ㅋㅋㅋ 재탕중...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (259,109,'carbbo',4,'4대강');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (260,110,'nucca',1,'간첩색휘들 애쓴다 밥은 먹고 다니냐?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (261,111,'julia',3,'좀 검증된 애들좀 출현시켜라이탈리아 특집 장난하냐');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (262,112,'tillo11',1,'아 정말짜증나네 절때보지말껄욕나옴');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (263,113,'samsam1',2,'슬프다 ㅠㅠ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (264,114,'hihi1123',5,'.최악의 환경속에서 이런 만화라도 만든사람들에게 경의를 보낸다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (265,115,'root',3,'What is this movie for?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (266,116,'roots',2,'여운이 엄청~길게 남는영화.. 이이경을 사랑하게하는 영화!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (267,117,'toor',5,'이딴게 한국 영화라니');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (268,118,'admin',5,'짜가인가 이게뭐여..뭔..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (269,119,'clio',2,'굿 10자 이상 .가나다라');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (270,120,'akas22',5,'짱이다ㅎ 혼자자식키우며살아온엄마 그의아들 힘들게살아오면서 서로예민해지고날카로워질때도잇엇지만 결국 ..가족ㅎ 아빠라는 사람도 생각보다최악이아니고..여자는, 확실히 요구하면도와준다는 그말이 왠지짠하게와닿는다ㅎ 나혼자괜히끙끙거리지말자ㅡ이런단순한생각이든다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (271,121,'olus',5,'CG도 별로고 전개도 별로고 연기도 별로고 한마디로 재미없다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (272,122,'bava',2,'번지수 잃고 갈팡질팡');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (273,123,'dita',4,'Yesterday when i was young');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (274,124,'erim1',2,'너무 사랑스럽고 감동적인 영화:) 정말 좋앗어요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (275,125,'guba',1,'최고의영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (276,126,'otto',2,'13년전 영활 다시보니 공효진 코평수줄이고 콧대높였네...완전 못생겼어 ㅎㅎ호 권상우는 화산고때 왼쪽 팔자 심하더니 지금 사라지고 더 잘생겨졌고 장혁은 멋지게 늙었네. ㅋㅋㅋ다시보니 웃겨');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (277,127,'euda',5,'말랑말랑 ...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (278,128,'mahga3',4,'공부 열심히 합시다 공부 안하면 저런 OO인생 삽니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (279,129,'leon',4,'그냥. 최고다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (280,130,'cosma123',5,'전쟁이후의 아픔을 잘 그린영화마지막 장면이 압권유대인줄 알아 더럽게 여기나 도움이 필요하니동행했던 토마스에게 더러운유태인이라고 말한장면 그러나 유대인인척한 사실 유대인가족사진을 보면서 미묘한 감정들을 사슴인형을 밟아까며 대변한다므찐영화^^');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (281,131,'carbbo',1,'오랜만에 동화다운 동화를 본 기분이다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (282,132,'nucca',1,'감사합니다 정말로 감사합니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (283,133,'julia',3,'걍 둘다 변태');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (284,134,'tillo11',2,'샤넬의 인생과 성공,이 아니라 샤넬과 그의 남자들');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (285,135,'samsam1',5,'영화가 내용이 없다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (286,136,'hihi1123',3,'십수년의 세월을 찰나의 순간처럼, 찰나의 순간을 영원한 기억으로 남기는 시간의 상대성 이론에 관하여.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (287,137,'root',2,'니노의 이중인격연기 두근거리네요♥');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (288,138,'roots',4,'보다가 울컥핫 영화...재미도 있고...먼가 감동적임');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (289,139,'toor',5,'열정만으로 돌진하고 싶게 만드는 영화.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (290,140,'admin',2,'연기력에서 유혹하지 못한다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (291,141,'clio',5,'난감하다. 재미도 없고, 세상을 깜짝 놀라게 하는 센세이션도 없다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (292,142,'akas22',3,'아무리 노력했어도 '차이나타운'을 대놓고 베낀 것은 용서가 안 됨.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (293,143,'olus',2,'신화 화이팅 에릭 화이팅>< 모두 힘내요 !');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (294,144,'bava',3,'엔딩이 넘 슬퍼요 :(');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (295,145,'dita',1,'영화관에 가서 보면 더 좋았을걸...어린시절로 돌아간 느낌이들어 만감이...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (296,146,'erim1',1,'정말 최고였어요 ㅠㅠ 이민정씨와 신하균씨 연기 너무 좋았어요!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (297,147,'guba',4,'몇 안되는 재밌게 본 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (298,148,'otto',5,'교양시간에 보고 좀 충격먹은 영화....마지막에 너무 슬펐다 빨갱이라 소리지르던 몬초가 갑자기 다른 단어를 말한건 선생님에대한 그리움 미안함 슬픔이었을까...몬초가 마지막에 좀 울먹인거 같기도 하고...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (299,149,'euda',2,'잘봤습니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (300,150,'mahga3',2,'안무서워!! 귀신이 애기라 그런건지,,, 그냥 깜놀하기만할뿐이야');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (301,1,'root',4,'뭐하자는건쥐... 모든것이 다 어설프고...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (302,1,'roots',4,'배우들의 따뜻한 연기도 일상의 힘겨움을 그리는 현실감도 다 좋았어요.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (303,1,'toor',5,'남자배우들 정말 미스캐스팅. 연기력 안습... 조은숙, 김유미 연기땜에 참고 봤다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (304,1,'admin',5,'1차 세계대전 中 피고 진 청춘들. 무기와 기술력은 20t세기, 전쟁을 일으킨 정치인들과 전쟁을 지휘하는 고위 장교들의 생각은 19세기.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (305,1,'clio',5,'책과는 분명히 다른시선. 괜찮네요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (306,1,'akas22',5,'내가 이거 왜 봤지 싶은데 한예슬이랑 김태희 나와서 본 듯. 적월도 개 쌤 ㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (307,2,'olus',2,'솔직히 6점때가 뭐냐 약간 더러운 장면만빼면 7.5정도다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (308,2,'bava',5,'와 이연서님 신인답지 않은 연기력 잘 봤습니다 다음 작품에서 또 뵙길 바랍니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (309,2,'dita',3,'반전이 전부가 아닌영화..몇 번을 봐도 또 보고 싶은 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (310,2,'erim1',4,'피해자만 있고,피의자는 없는 ..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (311,2,'guba',4,'개답답 먼주인공이 지혼자 복수도 못함?주변에서 해주길바라는 민폐녀?아직도 끌려다니고ㅡㅡ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (312,2,'otto',4,'신선한 소재. 화끈한 액션. 스피디한 전개');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (313,2,'euda',3,'이 영화의 3박자는 디테일이었다. (정말 시가전의 퀄리티는 완벽했고) 남자의 사랑에 대한 묘사... (작중에 한석규는 누군가를 사랑하는 마음은 정말 디테일이 대단했다.) 마지막 얘기의 완급조절이 완벽했다. 이 영화가 정말 멋졌다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (314,2,'mahga3',4,'탕웨이찡 그녀 만으로도 10점주기에 충분하다!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (315,3,'leon',5,'감동적인 영화다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (316,3,'cosma123',5,'당시 대박쳤던 영화..괜찮다!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (317,3,'carbbo',3,'억지스러운 시나리오..지루한 전개.. 1편 보다 못한 구성등.. 2편은 안나오는게 나았다..망작..배우들이 영화보는 눈이 없어서 안타깝다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (318,3,'nucca',5,'ㅋㅋㅋㅋㅋㅋㅋㅋ 반도 안되는 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (319,3,'julia',5,'이 영화가 평점이 높은 이유를 모르겠어..ㅡ.ㅡ::');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (320,4,'tillo11',5,'평생 기억할만한 영화,정상적인 소재는 아니지만');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (321,4,'samsam1',5,'요즘 상황 보고 이 영화가 생각났다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (322,4,'hihi1123',2,'많을 것을 생각하게 만드는 영화입니다.마지막에 사람들이 짐승으로 보이고 아수라가 사람같아 보였습니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (323,4,'root',3,'진짜 재미 없는 영화 공통점....스포츠영화,군대영화,자막 나오는 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (324,4,'roots',4,'로버트 드니로의 광기의 복수 연기를 만끽할수 있는 수작 서스펜스 스릴러물');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (325,5,'toor',2,'감동감동감동의 도가니탕');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (326,5,'admin',4,'세계 어디서나 정치 경제 문화 사회 전반에 걸쳐 변화가 절실한 상황이지만 변화를 가져올 방법이 없다는게 함정인 것 같다...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (327,5,'clio',5,'귀여운벤지.. 똑똑한 벤지 예쁘고 귀여운 친구... 압삘럽 ㅎ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (328,5,'akas22',2,'당시 개봉날 보고 울면서 나왔다. 돈아까워서..ㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (329,5,'olus',4,'정말 최고의 영화...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (330,5,'bava',4,'잔잔하게 숨막히는 영화 . 연출이 대단하다. 곳곳에 숨어있는 복선. 치밀하다 싶을정도로 섬세한 감정표현. 거기에 김영애의 연기까지');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (331,30,'dita',5,'once upon a dream');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (332,30,'erim1',5,'시나리오 연출 연기 어느것 하나 갖추지 못한 시간이 넘 아까운 억지 싸구려 중국 신파 경극...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (333,30,'guba',3,'거부하는 몸짓으로 저 하늘을 ~ ^^');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (334,30,'otto',2,'그만빙빙돌리고 밝혀지게하면안되나요 ?보려다아직도질질끌어짜증나.안봄 여기서또사고터져 또질질끌면진짜짜증날듯 ?빨리빨리밝혀질건밝혀지면서반전이있든지 ?작가님 이드라마사랑하고잼있는데 넘끌어짜증나요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (335,30,'euda',5,'졸면서 봤다 왜이리 평정이 높은겨 내용도 별거 없고 아오 감수성 영화냐 이거');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (336,30,'mahga3',3,'기대하지 않았던 영화의 아름다움이 밀려온다. 꽤 괜찮다았던 영화.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (337,30,'leon',4,'진짜 한번만더 이런영화 상영하면 용서하지 않는다지금 영화보면서 카톡하고잇음 아놔 진짜');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (338,31,'cosma123',1,'살아는 있지만 생동감을 잃은 박물관');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (339,31,'carbbo',3,'노땅들의 한심한 추억미화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (340,31,'nucca',3,'어릴적에 눈물흘리며 웃던기억에 간신히 찾아 다시 봤네요 ^^');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (341,31,'julia',2,'인종차별과 유괴라는 두주제의 불협화음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (342,31,'tillo11',5,'고명환이 연기가 쩌냐? 아니면 돈이 없어 쓴거냐..후자라면 볼가치가 없는영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (343,114,'samsam1',3,'속편에서는주인공이전작처럼앨빈의밴드였으면좋았을것같다.캐릭터추가로더이상해진듯');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (344,101,'hihi1123',2,'혼자 보긴 너무 아깝다. 2004년 올해의 영화.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (345,56,'root',4,'마지막 결투씬 최고! ㅋㅋ 폭풍눈물에~ 팝핀현준 할아버지 ㅋㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (346,96,'roots',4,'ㄵ 5점대asfgsdlgkbjsjvb');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (347,47,'toor',4,'좋아 상술최고..아니 선거술 최고...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (348,13,'admin',3,'쓰레기 함부로 버리지 맙시다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (349,86,'clio',3,'글쎄 나와는 안 맞는 성향의 영화 중 하나. OST는 들을 만함');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (350,135,'akas22',2,'즐~~~~~');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (351,31,'olus',1,'막장도 재미가있어야 보지..재미도 없고 짜증만 남남녀주인공이 어울리면 참고보겠는데 진짜 안어울리고웬만하면 다 재밌게 보는데 진짜 내가본것중 제일 최악이였음!!무튼 주인공들부터시작해서 성격 개 이상함!!조기종영이 답이다...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (352,104,'bava',1,'줄리델피는 나이가 들수록 멋지다!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (353,99,'dita',3,'내가 본 일드 중 쵝오~!!!!!>0<');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (354,20,'erim1',1,'역시 명작은 명작이다...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (355,79,'guba',3,'글쎄요.... 뭐랄까... 영화 제목을 잘못 보고 착각한 내 잘못이랄까...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (356,132,'otto',1,'그냥 기독교영화네요. 좀 더 깊이있는 내용을 기대했는데.. 실망입니다. 영화도 뭔가 엉성해요;;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (357,30,'euda',2,'그냥 책으로 읽는게 더 절절하게 다가온다. 영화는 내용을 너무 비약하고 삭제해서 행간을 잃어버렸다. 책에서 꽉 찼었던 느낌과 반대로 모든 것이 엉성하다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (358,86,'mahga3',2,'너무나 감동적인 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (359,53,'leon',2,'스킨헤드성님들이 이 영화를 싫어합니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (360,23,'cosma123',1,'자동차 매니아인 나의 평점은 5점 이하~속았다...아오~');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (361,84,'carbbo',5,'나 이거 보고 인형 절대안삼');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (362,135,'nucca',2,'정체성은 사치인가?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (363,13,'julia',1,'나이먹은아저씨들이 일찐놀이하는영화 개역겹다. 알바풀었냐 현실감 개진짜 개제로');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (364,78,'tillo11',1,'남극은 왔는데 그만 길을 잃었다. 오르지 못할 곳은 오르는 것이 아니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (365,14,'samsam1',3,'재밌음 귀엽고 신남');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (366,134,'hihi1123',1,'포스터는 진심 개쩐다~ 엑소시스트를 능가하는 공포물 같지만 실상은 처키보다 못한영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (367,113,'root',3,'시청률 44%는 개뿔;; 존11나 재미없어;; 이제보니 MBC가 사극너무못만드네;;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (368,22,'roots',1,'요즘 재방보는데 넘 재밌는데...왜 시청률은 저조했을까 싶네요...둘다 귀요미');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (369,87,'toor',1,'연출 연기 영상이 아름다운 영화입니다. 저예산영화인 관계로 스펙타클은 부족하지만 한국영화계에 새로운 바람, 희망, 다크호스가 될것임을 믿습니다. 많은 응원부탁드리고 벌써부터 일찍 관람해주신분들 진심으로 감사합니다. New hope');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (370,122,'admin',3,'평점이왜이렇게낮지?난 이거 또다운받고있다.3번째...정말잼있던데...끝에 견자단하고 대빵하고싸울땐 정말 가슴이뜨거워졌다.난정말로 잼있게봤다...최근댓글이니 내가 알바아닌줄은 알거다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (371,125,'clio',2,'이게 어떻게 평점이 낮을수가 있지?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (372,55,'akas22',2,'블랙코미디 조롱 대상이 우린데 기분 드러워서 점수 주겠냐? 성기 노출 등으로 어그로나 끌고서는 ㅉㅉ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (373,77,'olus',5,'촌동네 조폭삼류영화. 가끔씩 툭툭들이미는 유머도 영쌩뚱맞구 촌스럽기까지하다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (374,64,'bava',1,'10점 만들기');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (375,145,'dita',5,'스타뎀 형님의 얼굴에 먹칠을 한영화..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (376,9,'erim1',3,'헐...남자몸매보면 기분 좋나?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (377,110,'guba',3,'안봐도 별점 한개 주고싶은 10류 영화 같다... ㅋㅋ심형래 아저씨와 동급감독인듯 ㅋㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (378,28,'otto',1,'정말 완벽했다.최고의 영화중에 꼽히는 영화.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (379,51,'euda',5,'조잡하고 유치한 저예산 3류 B급 영화다.. 스토리에 깊이감도 없고 전체적으로 루즈하다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (380,75,'mahga3',1,'진짜..뭐냐 민국이나 지아는 더빙 더이상시키면안되겠네 더빙이 얼마나중요한데 이런애들을시켜데뷔도안한애들을 연예인이해도 뭐라고하는판에');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (381,136,'leon',3,'그냥 재미가 없어요....ㅠㅠ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (382,43,'cosma123',4,'쇼를해라 쇼');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (383,20,'carbbo',4,'중심이 약하니 언저리 가지고 무리한 승부수를 띄운다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (384,115,'nucca',3,'주연배우들의 이름만 기억에 남.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (385,77,'julia',5,'그냥 안보는게 이득 ...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (386,98,'tillo11',4,'키기키기키기키기키기');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (387,57,'samsam1',1,'박얘쁜 빠수니 죄다 OO 없어져버려');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (388,24,'hihi1123',5,'진짜 짜증나는 영화..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (389,18,'root',3,'불은 잘 보이지도 않고 사람 죽어나갈 때는 엄청난 웅장한 음악만 나오고 전혀 마음에 와 닿지 않는 설정들');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (390,90,'roots',1,'망작');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (391,98,'toor',1,'상당히 재밌게 봤습니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (392,49,'admin',2,'내코끼리내놔가 더재밌음ㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (393,100,'clio',4,'코믹은 코믹으로 봐라 패러디하고 카메오들보는 재미도 있다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (394,50,'akas22',5,'유치짬뽕이네!!. 딱 초등3학년 영화다. 초등학교 자녀 있는 가족분께 추천함!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (395,47,'olus',3,'후속 지금이라도 나와라 한국애니 좀 살려보자');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (396,65,'bava',2,'EBS를 통해 봤는데.. 정말 재밌게 잘 봤어요. 요 근래 본 영화 중 최고인듯!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (397,148,'dita',3,'기대않고 봤는데, 찰지게 만든 토종느와르네~! 흥미진진하다..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (398,123,'erim1',3,'성인영화를 가족영화로 만드려하는 멍청한 자막제작자가 마음에 안들어서 1점');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (399,44,'guba',2,'일본인 특유의 어색한 연기 여주인공 연기 너무 못해');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (400,123,'otto',4,'전반적으로 무거운 느낌의 영화네요.가비의향과맛처럼,씁쓸함이 느껴집니다.장윤현감독님께서,커피부분에관해 신경을 쓰시다보니,연출부분에있어서,좀 미흡하지않았나싶고, 배우들연기력은 괜찮았습니다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (401,28,'euda',2,'전작보다 100 재밌다. 배우, 내용 모두 세련됨');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (402,13,'mahga3',3,'진지하고 무거운 소재를 경쾌하고 재미있게 만들었다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (403,61,'leon',5,'유럽작품상 탈만한 유럽에 중요한 얘기..또한 픽션');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (404,142,'cosma123',3,'풍정정은 어케된거지ㅋㅋㅋ과도한 압축으로 개연성없지만...배우들이 호화로워서...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (405,71,'carbbo',2,'이영화 구성좋다는분들 ㅋㅋ아마 친구랑 같이영화보고 님들이 영화 좋다고 재밌다하면 같이본 친구들은 이해하지 못할겁니다 ㅋㅋ진짜 최악 최저 스토리 주인공 행동 개연성없음캐릭간의 이해관계 최악 ㅋㅋㅋCIA갘ㅋㅋ이렇게 허접하게 표현된 영화 간만이라능ㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (406,76,'nucca',4,'이젠 그만 보고 싶은, 막돼먹은 스토리텔링.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (407,62,'julia',4,'말이 필요 없다.로맨스 싫어하는 내가 봤을때 기절할 것 같았어 ㅜㅜㅜㅜ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (408,137,'tillo11',1,'제 취향적 이고 우울한 마음을 완전히 날려버리고 슬픈내용을 본뒤 마음을 정화시켜주네요.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (409,86,'samsam1',2,'영상미가 역시 최고네요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (410,15,'hihi1123',3,'끙.....');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (411,30,'root',1,'역시 한국영화는 보지말아야돼');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (412,150,'roots',1,'괜찮은 영화...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (413,110,'toor',5,'요즘 재밌음!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (414,49,'admin',1,'소재는 참 좋아서 삼점준다. 제작된 영화는 공포도, 스릴러도 아닌 본분을 잊은 드라마아닌 드라마같은 느낌이다. 연기, 연출은 괜찮았다. 다만 시작부터 끝까지 지루할 뿐이다. 또 어떤 장면들은 살짝 유치했다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (415,142,'clio',1,'남자인데 보는내내 울었다 딸 낳으면 잘해줘야지...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (416,91,'akas22',3,'안타까울뿐. 안타까울뿐.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (417,7,'olus',2,'영웅은 사람들이 원하기 때문에 만들어지는 또다른 희생자다..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (418,122,'bava',5,'그냥 평작. 욕까진안나오고..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (419,19,'dita',5,'극장가서 안본 내머리를 깨버리고싶네요. 제인생 최고의 영홥니다. 키이라작품 중에서도 최고일듯. 알럽키이라♡♡');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (420,110,'erim1',4,'중고생들의 마마추어 포르노');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (421,48,'guba',4,'비디오 물이냐 동시상영물이냐 ~ 넌 정체가 모냐');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (422,116,'otto',5,'이건 말로 설명할 수 없는 유치함이다. 진짜 필름이 아깝다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (423,83,'euda',1,'이승연의 강렬함이 묻어나는 영화. 그러나 홍경인은 너무 불쌍하게 나옴');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (424,98,'mahga3',3,''드릴브라' 에서 뿜었다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (425,65,'leon',2,'2% 부족한 영화가아닌 98%부족한 영화감동이 있다길래 참고 끝까지 다봤는데...;;진심으로 이렇게 재미없다고 느끼는건 처음;;');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (426,39,'cosma123',4,'계몽영화의 한계를 고스란이 답습한다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (427,132,'carbbo',1,'우와 정말 오랜만에 통쾌하게 웃었네요 ㅎㅎ 내일이 기대됩니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (428,84,'nucca',1,'청춘에는 마침표가 없다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (429,13,'julia',3,'세얼간이 아줌마 나와서 한번 본건데 실망...신선한 반전을 주고싶었나 본데 개연성도 없구 뭐이런...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (430,91,'tillo11',2,'좋은 소재에 만족할 연출.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (431,27,'samsam1',2,'심혜진이 나와서 겨우 저정도라니 실망이다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (432,31,'hihi1123',3,'아들놈은 끝까지 아빠한테 미안한 감정 없어..ㅠ 소재가 신선했는데 영화 자체는 메시지도 모호하고 스토리가 짜임새 있지 않은 것 같다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (433,144,'root',4,'창업을 꿈꾸는가! 좋은 아이템이 있어 사업을 하려하는가!! 그렇다면 기를 쓰고 이 영활 보기바란다!! 그 멀고 험한 여정에 스승이 될것이요 지침서가 될것이다... 혹은 단념에 도움이 될지도... 참 오랜만에 박장대소하며 본 독립영활세~~~ ★');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (434,99,'roots',1,'슬픈액션영화치고는실망이크다부자간의배신과원망으로끝나는것이너무허무하다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (435,103,'toor',3,'EBS 명화에서 이거보고 움 진짜감동적');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (436,126,'admin',3,'낰였다 티 프리미엄ㅡㅡ 인간적인 면이 쫌 맘에 들어서 2점줬다 근데 진짜 이선균 정재영 김상중 연기파배우들 불러노코 이딴 쓰레기 영화 찍냐ㅡㅡ 진짜 영화보는데 계쇠 지루하고 괴로웠다ㅡㅡ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (437,130,'clio',3,'너무나 따뜻하고 감동적인 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (438,58,'akas22',1,'C급영화도 안되는...일점도 아깝다... 네이버는 마이너스 점수도 만들어 달라');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (439,142,'olus',3,'스토리의 부진은 액션의 재미까지 반감시킨다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (440,109,'bava',3,'누구나 ㅡ낄수ㅣㅆ느덕을 영화화함...굿,,');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (441,70,'dita',3,'시종일관 오락가락 말하고자하는게 뭔지 모르겠다 감독자기만의 세계에 빠져 만든것같은 영화..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (442,103,'erim1',1,'왠지모를 색다른 감동을 주는영화이다....');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (443,112,'guba',2,'전주영화제에서봤었는데넘늦게개봉한듯... 종교와업에대해한번더생각할수있게만든영화. 저예산으로만들었으나감독의노력이느껴져큰박수를보내고싶다. 화이팅!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (444,56,'otto',3,'보는내내 웃었습니다 재밌네요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (445,115,'euda',1,'1');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (446,75,'mahga3',4,'사랑에 상처받으면 다시 치유될수 있을까? 하는 생각이 드는 영화!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (447,106,'leon',1,'극장가서 본영화중 쓰디쓴아픔을 처음으로 느끼게해준 퍼스트');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (448,28,'cosma123',1,'최고! 더 무슨평가가 필요한가 ~~탑!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (449,113,'carbbo',2,'자신의삶에대해 다시한번 생각하게하는영화...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (450,86,'nucca',3,'알바놈들 양심도 없냐...멀보고 십점주는거냐');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (451,105,'julia',4,'90년도로 돌아가게 해준다는 ㅡㅡ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (452,36,'tillo11',4,'끼워 맞추기 개쩔던데, 반전 하나 보고 와 하는 인간들 이해 불가');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (453,97,'samsam1',4,'우웩. 개랑 무슨짓을 했길래. 후세가 태어나. 일본놈들 진짜 정신상태 이상하네.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (454,36,'hihi1123',5,'우웩. 개랑 무슨짓을 했길래. 후세가 태어나. 일본놈들 진짜 정신상태 이상하네.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (455,14,'root',3,'이 영활 보고나면 흐뭇해진다.. 영화는 한국이 더 잘만든다는 걸 느끼게 되니까..');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (456,37,'roots',5,'지들이 뭔데 대우를 까냐?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (457,62,'toor',5,'재밌고 짠하고 그게 매력입니다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (458,73,'admin',4,'와 ㅠㅠ 내머릿속지우개 이후에 진짜 슬픈영화였어요 ㅠㅠ 마지막에 눈물폭발 ㅜㅜ 오늘이후에도 또보고싶네요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (459,113,'clio',2,'월요커플 짱짱!! 덕분에 아주 재미있게 보고 있습니당!!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (460,72,'akas22',1,'007 터키특집..액션은 스키추격이 기억에 남고. 소피의,소피에 의한,소피를 위한 시리즈..로저무어 시절보다 재미는 조금 떨어진다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (461,9,'olus',1,'수많은 최루성 멜로는 여기에서...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (462,100,'bava',5,'내평생 최고의 걸작. 현실 건너편 세계를 잠시 엿본듯한 느낌.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (463,84,'dita',3,'내 인생 최고의 영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (464,21,'erim1',3,'진짜 추천해요 ^^');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (465,75,'guba',3,'포스터가 사기. 너무 현실적이어서 배우들은 심각한데 빵빵 터지는 화성남 금성녀. 아 슈발 지는 혼자 내리면서 본전생각에 담배 피는 남편.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (466,143,'otto',2,'머가마술이라는거야?나죽기전에외계인만나볼수나있을지?');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (467,109,'euda',1,'참 재밌는 영화 ㅎㅎ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (468,51,'mahga3',4,'빨리좀 끝나라...으이그 처음엔재밌는줄알았는데이게뭐야!이리재미없다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (469,13,'leon',4,'극에 전혀 몰입안되는 장면 이어붙이기식 단순 진행,연출력이 형편없음.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (470,50,'cosma123',2,'자막제작자가 써놨듯이 막장임.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (471,42,'carbbo',3,'그리 무서운 수도승이 물에 쉽게 떠내려가네');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (472,129,'nucca',4,'이게왜 주온보다 평점이높은지 이해가안간다 이영화 맨처음 여배우가 물대포쏠때부터 웃겻다 포스터가 더무섭다 영화상영시간내내 포스터만보여줘도 충분히지린다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (473,145,'julia',3,'진짜 신기하다...라는 말밖에 안나와');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (474,13,'tillo11',2,'좋은 배우들을 데리고....;; 작품의 부족함.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (475,94,'samsam1',1,'아니 왜 5점대라니, 근래에 본 다크 히어로무비 중에서 최고였어요. 아주 그냥 고스트라이더에게 걸리면 스치면 사망인거에요.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (476,133,'hihi1123',2,'묵직하게 시작해서 우습게 끝남');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (477,21,'root',4,'내용 전개가엉성하고지루할정도로 재미가없슴');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (478,4,'roots',3,'돈뭉치로 싸대기;; 명장면이다ㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (479,35,'toor',2,'2.2고고하자 ㅋㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (480,70,'admin',3,'쓰레기영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (481,122,'clio',3,'너무일찍슬픔을알게된제제가안쓰럽다..책으로읽고도눈물이났는데..영화도마찬가지다.어린나이의제제는슬픔을너무일찍알아버렸다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (482,125,'akas22',4,'정말 비디오마저 돈주고 보고 아깝다..최악...');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (483,91,'olus',4,'말그대로 뚝방에서 볼영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (484,143,'bava',5,'내 인생 최고의 영화. 10년이 다되가는데, 아직도 아련하고 애틋한 기억.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (485,24,'dita',1,'감독ㅡㅡ다신영화찍지마라');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (486,57,'erim1',1,'육감적인 섹시한 여인들의 존재 자체가 이 영화의 전부');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (487,38,'guba',5,'영화 첫 도입부 부터 카메라 각도라든지 화질이라든지 겁나 구림.. 영화 아닌줄 알았음');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (488,23,'otto',4,'진정 좋은 영화란 볼때당시 잼있다... 도 있지만.. 두고두고 기억나고생각나고 또 한번쯤 보고싶은 이런영화가 아닐런지요 ㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (489,96,'euda',5,'박사아들 정시현 정말 멋져요');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (490,59,'mahga3',5,'1편이 너무좋아서 2편이 너무묻힌다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (491,114,'leon',4,'할 말이 없다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (492,38,'cosma123',3,'난 별로던데 -_ -');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (493,77,'carbbo',5,'이런 영화가 참 좋다.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (494,42,'nucca',1,'곳곳에 번뜩이는 아이디어. 아기자기한 구성이 돋보이는 수작.');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (495,2,'julia',4,'우아....새벽에보니까 무섭네 ㅠ_ㅠ 미스터리와에로스와 스릴러를 겸비한 영화!');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (496,65,'tillo11',3,'짧지만 정말 재밌게 잘봤어요~. 윤계상 능청연기 좋구 잘됬으면 하는 생각을 계속 했네요~ ㅋㅋ');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (497,119,'samsam1',3,'에린이 초반에 타던차 현대자동차 프레스토 네요. 보면서 추억이세록세록');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (498,63,'hihi1123',5,'남들이 철학적인 영화라고도 하지만 단순 액션용으로 봐도 이 정도 점수는 나와야된다');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (499,43,'bava',5,'말그대로 뚝방에서 볼영화');
INSERT INTO bcomment (cno,bno,userid,cstar,ccontent) VALUES (500,13,'dita',2,'내 인생 최고의 영화. 10년이 다되가는데, 아직도 아련하고 애틋한 기억.');
